In [1]:
# ROOT PATH

import sys
import os

project_root = os.path.abspath("..")

if project_root not in sys.path:
    sys.path.append(project_root)

In [2]:
# IMPORTS

import pandas as pd
import numpy as np

In [3]:
# FAST LOAD YELP SUBSET

yelp_df = pd.read_json(
    "../data/raw/yelp/yelp_academic_dataset_review.json",
    lines=True,
    nrows=5000
)

print(yelp_df.shape)

yelp_df.head()

(5000, 9)

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3,0,0,0,"If you decide to eat here, just be aware it is...",2018-07-07 22:09:11
1,BiTunyQ73aT9WBnpR9DZGw,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,5,1,0,1,I've taken a lot of spin classes over the year...,2012-01-03 15:28:18
2,saUsX_uimxRlCVr67Z4Jig,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,3,0,0,0,Family diner. Had the buffet. Eclectic assortm...,2014-02-05 20:30:30
3,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5,1,0,1,"Wow! Yummy, different, delicious. Our favo...",2015-01-04 00:01:03
4,Sx8TMOWLNuJBWer-0pcmoA,bcjbaE6dDog4jkNY91ncLQ,e4Vwtrqf-wpJfwesgvdgxQ,4,1,0,1,Cute interior and owner (?) gave us tour of up...,2017-01-14 20:54:15

In [4]:
lagos_df = pd.read_csv(
    "../data/external/clean_lagos_restaurants.csv"
)

lagos_df.head()

,Unnamed: 0,author_name,review_title,review_text,author_rating,visit_date,overall_rating,restaurant_name
0,0,N9599MZaisham,Less than basic taste,For a brand that claims to have one of the bes...,2.0,01/09/2022,2.0,01 Shawarma
1,1,T-Africa2000,Much improved,We had a business dinner at 1415 this week and...,4.0,01/01/2020,4.0,1415 Steakhouse Seafood Restaurant
2,2,sunilt1960,Calm and Relaxing,Had dinner at this restaurant while staying in...,4.5,01/02/2019,4.0,1415 Steakhouse Seafood Restaurant
3,3,ooobabatunde,Better,Thank you for staying with us in Eko Hotels & ...,4.5,01/01/2019,4.0,1415 Steakhouse Seafood Restaurant
4,4,MrTraveller420,1415 Steakhouse,Went over to the old location of the Steakhous...,4.0,01/11/2018,4.0,1415 Steakhouse Seafood Restaurant

In [5]:
# goodreads dataset loading

books_df = pd.read_json(
    "../data/raw/goodreads/goodreads_reviews_dedup.json",
    nrows=5000,
    lines=True
)

books_df.head()

,user_id,book_id,review_id,rating,review_text,date_added,date_updated,read_at,started_at,n_votes,n_comments
0,8842281e1d1347389f2ab93d60773d4d,24375664,5cd416f3efc3f944fce4ce2db2290d5e,5,Mind blowingly cool. Best science fiction I've...,Fri Aug 25 13:55:02 -0700 2017,Mon Oct 09 08:55:59 -0700 2017,Sat Oct 07 00:00:00 -0700 2017,Sat Aug 26 00:00:00 -0700 2017,16,0
1,8842281e1d1347389f2ab93d60773d4d,18245960,dfdbb7b0eb5a7e4c26d59a937e2e5feb,5,This is a special book. It started slow for ab...,Sun Jul 30 07:44:10 -0700 2017,Wed Aug 30 00:00:26 -0700 2017,Sat Aug 26 12:05:52 -0700 2017,Tue Aug 15 13:23:18 -0700 2017,28,1
2,8842281e1d1347389f2ab93d60773d4d,6392944,5e212a62bced17b4dbe41150e5bb9037,3,I haven't read a fun mystery book in a while a...,Mon Jul 24 02:48:17 -0700 2017,Sun Jul 30 09:28:03 -0700 2017,Tue Jul 25 00:00:00 -0700 2017,Mon Jul 24 00:00:00 -0700 2017,6,0
3,8842281e1d1347389f2ab93d60773d4d,22078596,fdd13cad0695656be99828cd75d6eb73,4,"Fun, fast paced, and disturbing tale of murder...",Mon Jul 24 02:33:09 -0700 2017,Sun Jul 30 10:23:54 -0700 2017,Sun Jul 30 15:42:05 -0700 2017,Tue Jul 25 00:00:00 -0700 2017,22,4
4,8842281e1d1347389f2ab93d60773d4d,6644782,bd0df91c9d918c0e433b9ab3a9a5c451,4,A fun book that gives you a sense of living in...,Mon Jul 24 02:28:14 -0700 2017,Thu Aug 24 00:07:20 -0700 2017,Sat Aug 05 00:00:00 -0700 2017,Sun Jul 30 00:00:00 -0700 2017,8,0

In [6]:
# loading amazon grocery dataset
grocery_df = pd.read_json(
    "../data/raw/amazon/grocery_and_gourmet_food.json",
    lines=True,
    nrows=5000
)

grocery_df.head()

,overall,verified,reviewTime,reviewerID,asin,reviewerName,reviewText,summary,unixReviewTime,vote,image,style
0,5,True,"06 4, 2013",ALP49FBWT4I7V,1888861614,Lori,Very pleased with my purchase. Looks exactly l...,Love it,1370304000,NaN,NaN,NaN
1,4,True,"05 23, 2014",A1KPIZOCLB9FZ8,1888861614,BK Shopper,Very nicely crafted but too small. Am going to...,Nice but small,1400803200,NaN,NaN,NaN
2,4,True,"05 9, 2014",A2W0FA06IYAYQE,1888861614,daninethequeen,still very pretty and well made...i am super p...,"the ""s"" looks like a 5, kina",1399593600,NaN,NaN,NaN
3,5,True,"04 20, 2014",A2PTZTCH2QUYBC,1888861614,Tammara,"I got this for our wedding cake, and it was ev...",Would recommend this to a friend!,1397952000,NaN,NaN,NaN
4,4,True,"04 16, 2014",A2VNHGJ59N4Z90,1888861614,LaQuinta Alexander,It was just what I want to put at the top of m...,Topper,1397606400,NaN,NaN,NaN

In [7]:
# loading amazon home and kitchen dataset

home_df = pd.read_json(
    "../data/raw/amazon/home_and_kitchen.json",
    lines=True,
    nrows=5000
)

home_df.head()

,overall,vote,verified,reviewTime,reviewerID,asin,reviewerName,reviewText,summary,unixReviewTime,style,image
0,5,2.0,True,"08 31, 2010",A3NSN9WOX8470M,0006564224,mmm,"I don't use these for their original use, and ...",Many uses...,1283212800,NaN,NaN
1,5,2.0,True,"04 2, 2010",A2AMX0AJ2BUDNV,0006564224,John R. Welch,"Seems a bit expensive for a plastic bottle, bu...",Dispenser bottle,1270166400,NaN,NaN
2,5,NaN,True,"11 5, 2015",A8LUWTIPU9CZB,0560467893,Linda Fahner,"Great product, love it!!",Five Stars,1446681600,NaN,NaN
3,4,4.0,True,"10 29, 2015",AABKIIHAL0L66,0560467893,TheBlueChain,This is a sturdy floating corner shelf! We mo...,"Sturdy Shelf, Poor Installation Instructions",1446076800,NaN,NaN
4,3,NaN,True,"09 9, 2015",A3DA0KIQ5OBK5C,0560467893,angelaarden,I purchased 4 of these shelves. they look grea...,Look great - one bad one...,1441756800,NaN,NaN

In [8]:
import os

os.makedirs(
    "../data/curated/restaurants",
    exist_ok=True
)

os.makedirs(
    "../data/curated/books",
    exist_ok=True
)

os.makedirs(
    "../data/curated/products",
    exist_ok=True
)

In [9]:
# CACHE YELP SUBSET
yelp_df.to_csv(
    "../data/curated/restaurants/yelp_subset.csv",
    index=False
)

print("Yelp subset cached successfully.")

Yelp subset cached successfully.

In [10]:
# CACHE GOODREADS SUBSET
books_df.to_csv(
    "../data/curated/books/goodreads_subset.csv",
    index=False
)
print("Goodreads subset cached successfully.")

Goodreads subset cached successfully.

In [11]:
# CACHE AMAZON GROCERY SUBSET
grocery_df.to_csv(
    "../data/curated/products/grocery_subset.csv",
    index=False
)
print("Amazon grocery subset cached successfully.")

Amazon grocery subset cached successfully.

In [12]:
# CACHE AMAZON HOME SUBSET
home_df.to_csv(
    "../data/curated/products/home_subset.csv",
    index=False
)
print("Amazon home subset cached successfully.")

Amazon home subset cached successfully.

In [13]:
print("YELP:", yelp_df.shape)

print("LAGOS:", lagos_df.shape)

print("GOODREADS:", books_df.shape)

print("GROCERY:", grocery_df.shape)

print("HOME:", home_df.shape)

YELP: (5000, 9)
LAGOS: (8294, 8)
GOODREADS: (5000, 11)
GROCERY: (5000, 12)
HOME: (5000, 12)

In [14]:
print("YELP COLUMNS")
print(yelp_df.columns)

print("\n")

print("LAGOS COLUMNS")
print(lagos_df.columns)

print("\n")

print("GOODREADS COLUMNS")
print(books_df.columns)

print("\n")

print("GROCERY COLUMNS")
print(grocery_df.columns)

print("\n")

print("HOME COLUMNS")
print(home_df.columns)

YELP COLUMNS
Index(['review_id', 'user_id', 'business_id', 'stars', 'useful', 'funny',
       'cool', 'text', 'date'],
      dtype='str')


LAGOS COLUMNS
Index(['Unnamed: 0', 'author_name', 'review_title', 'review_text',
       'author_rating', 'visit_date', 'overall_rating', 'restaurant_name'],
      dtype='str')


GOODREADS COLUMNS
Index(['user_id', 'book_id', 'review_id', 'rating', 'review_text',
       'date_added', 'date_updated', 'read_at', 'started_at', 'n_votes',
       'n_comments'],
      dtype='str')


GROCERY COLUMNS
Index(['overall', 'verified', 'reviewTime', 'reviewerID', 'asin',
       'reviewerName', 'reviewText', 'summary', 'unixReviewTime', 'vote',
       'image', 'style'],
      dtype='str')


HOME COLUMNS
Index(['overall', 'vote', 'verified', 'reviewTime', 'reviewerID', 'asin',
       'reviewerName', 'reviewText', 'summary', 'unixReviewTime', 'style',
       'image'],
      dtype='str')

In [15]:
# STANDARDIZE YELP
# For the sake of this example, we'll standardize the Yelp dataset to have the following columns:
# - domain: The source domain (e.g., "yelp")
# - user_id: The ID of the user who wrote the review
# - item_id: The ID of the item being reviewed (e.g., business_id for Yelp)
# - review_text: The text of the review
# - rating: The rating given by the user (e.g., stars for Yelp)
# - timestamp: The time when the review was written

yelp_standardized = pd.DataFrame({

    "domain": "yelp",

    "user_id":
        yelp_df["user_id"],

    "item_id":
        yelp_df["business_id"],

    "review_text":
        yelp_df["text"],

    "rating":
        yelp_df["stars"],

    "timestamp":
        yelp_df["date"]
})

yelp_standardized.head()

,domain,user_id,item_id,review_text,rating,timestamp
0,yelp,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,"If you decide to eat here, just be aware it is...",3,2018-07-07 22:09:11
1,yelp,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,I've taken a lot of spin classes over the year...,5,2012-01-03 15:28:18
2,yelp,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,Family diner. Had the buffet. Eclectic assortm...,3,2014-02-05 20:30:30
3,yelp,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,"Wow! Yummy, different, delicious. Our favo...",5,2015-01-04 00:01:03
4,yelp,bcjbaE6dDog4jkNY91ncLQ,e4Vwtrqf-wpJfwesgvdgxQ,Cute interior and owner (?) gave us tour of up...,4,2017-01-14 20:54:15

In [16]:
# STEP 2 — STANDARDIZE LAGOS

lagos_standardized = pd.DataFrame({

    "domain": "lagos_restaurants",

    "user_id":
        lagos_df["author_name"],

    "item_id":
        lagos_df["restaurant_name"],

    "review_text":
        lagos_df["review_text"],

    "rating":
        lagos_df["overall_rating"],

    "timestamp":
        lagos_df["visit_date"]
})

lagos_standardized.head()

,domain,user_id,item_id,review_text,rating,timestamp
0,lagos_restaurants,N9599MZaisham,01 Shawarma,For a brand that claims to have one of the bes...,2.0,01/09/2022
1,lagos_restaurants,T-Africa2000,1415 Steakhouse Seafood Restaurant,We had a business dinner at 1415 this week and...,4.0,01/01/2020
2,lagos_restaurants,sunilt1960,1415 Steakhouse Seafood Restaurant,Had dinner at this restaurant while staying in...,4.0,01/02/2019
3,lagos_restaurants,ooobabatunde,1415 Steakhouse Seafood Restaurant,Thank you for staying with us in Eko Hotels & ...,4.0,01/01/2019
4,lagos_restaurants,MrTraveller420,1415 Steakhouse Seafood Restaurant,Went over to the old location of the Steakhous...,4.0,01/11/2018

In [17]:
# STEP 3 — STANDARDIZE GOODREADS

goodreads_standardized = pd.DataFrame({

    "domain": "goodreads",

    "user_id":
        books_df["user_id"],

    "item_id":
        books_df["book_id"],

    "review_text":
        books_df["review_text"],

    "rating":
        books_df["rating"],

    "timestamp":
        books_df["date_added"]
})

goodreads_standardized.head()

,domain,user_id,item_id,review_text,rating,timestamp
0,goodreads,8842281e1d1347389f2ab93d60773d4d,24375664,Mind blowingly cool. Best science fiction I've...,5,Fri Aug 25 13:55:02 -0700 2017
1,goodreads,8842281e1d1347389f2ab93d60773d4d,18245960,This is a special book. It started slow for ab...,5,Sun Jul 30 07:44:10 -0700 2017
2,goodreads,8842281e1d1347389f2ab93d60773d4d,6392944,I haven't read a fun mystery book in a while a...,3,Mon Jul 24 02:48:17 -0700 2017
3,goodreads,8842281e1d1347389f2ab93d60773d4d,22078596,"Fun, fast paced, and disturbing tale of murder...",4,Mon Jul 24 02:33:09 -0700 2017
4,goodreads,8842281e1d1347389f2ab93d60773d4d,6644782,A fun book that gives you a sense of living in...,4,Mon Jul 24 02:28:14 -0700 2017

In [18]:
#STEP 4 — STANDARDIZE AMAZON GROCERY


# STANDARDIZE AMAZON GROCERY

grocery_standardized = pd.DataFrame({

    "domain": "amazon_grocery",

    "user_id":
        grocery_df["reviewerID"],

    "item_id":
        grocery_df["asin"],

    "review_text":
        grocery_df["reviewText"],

    "rating":
        grocery_df["overall"],

    "timestamp":
        grocery_df["reviewTime"]
})

grocery_standardized.head()

,domain,user_id,item_id,review_text,rating,timestamp
0,amazon_grocery,ALP49FBWT4I7V,1888861614,Very pleased with my purchase. Looks exactly l...,5,"06 4, 2013"
1,amazon_grocery,A1KPIZOCLB9FZ8,1888861614,Very nicely crafted but too small. Am going to...,4,"05 23, 2014"
2,amazon_grocery,A2W0FA06IYAYQE,1888861614,still very pretty and well made...i am super p...,4,"05 9, 2014"
3,amazon_grocery,A2PTZTCH2QUYBC,1888861614,"I got this for our wedding cake, and it was ev...",5,"04 20, 2014"
4,amazon_grocery,A2VNHGJ59N4Z90,1888861614,It was just what I want to put at the top of m...,4,"04 16, 2014"

In [19]:
# STEP 5 — STANDARDIZE AMAZON HOME

home_standardized = pd.DataFrame({

    "domain": "amazon_home",

    "user_id":
        home_df["reviewerID"],

    "item_id":
        home_df["asin"],

    "review_text":
        home_df["reviewText"],

    "rating":
        home_df["overall"],

    "timestamp":
        home_df["reviewTime"]
})

home_standardized.head()

,domain,user_id,item_id,review_text,rating,timestamp
0,amazon_home,A3NSN9WOX8470M,0006564224,"I don't use these for their original use, and ...",5,"08 31, 2010"
1,amazon_home,A2AMX0AJ2BUDNV,0006564224,"Seems a bit expensive for a plastic bottle, bu...",5,"04 2, 2010"
2,amazon_home,A8LUWTIPU9CZB,0560467893,"Great product, love it!!",5,"11 5, 2015"
3,amazon_home,AABKIIHAL0L66,0560467893,This is a sturdy floating corner shelf! We mo...,4,"10 29, 2015"
4,amazon_home,A3DA0KIQ5OBK5C,0560467893,I purchased 4 of these shelves. they look grea...,3,"09 9, 2015"

In [20]:
# STEP 6 — COMBINE ALL DOMAINS

unified_behavior_df = pd.concat([

    yelp_standardized,

    lagos_standardized,

    goodreads_standardized,

    grocery_standardized,

    home_standardized

],
ignore_index=True)

unified_behavior_df.head()

,domain,user_id,item_id,review_text,rating,timestamp
0,yelp,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,"If you decide to eat here, just be aware it is...",3.0,2018-07-07 22:09:11
1,yelp,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,I've taken a lot of spin classes over the year...,5.0,2012-01-03 15:28:18
2,yelp,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,Family diner. Had the buffet. Eclectic assortm...,3.0,2014-02-05 20:30:30
3,yelp,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,"Wow! Yummy, different, delicious. Our favo...",5.0,2015-01-04 00:01:03
4,yelp,bcjbaE6dDog4jkNY91ncLQ,e4Vwtrqf-wpJfwesgvdgxQ,Cute interior and owner (?) gave us tour of up...,4.0,2017-01-14 20:54:15

In [21]:
print(
    unified_behavior_df.shape
)

unified_behavior_df["domain"].value_counts()

(28294, 6)

domain
lagos_restaurants    8294
yelp                 5000
goodreads            5000
amazon_grocery       5000
amazon_home          5000
Name: count, dtype: int64

NEW ARCHITECTURE:

Unified Cross-Domain Behavior
→ Existing Archetypes
→ Expanded Behavioral Signals
→ Cross-domain reasoning

In [22]:
persona_df = pd.read_csv(
    "../outputs/persona_dataset.csv"
)

persona_df.head(12)

,user_id,avg_rating,rating_variance,review_count,avg_review_length,avg_sentiment,sentiment_variance,cluster,archetype,dominant_value
0,-EX1hrPRBqNkVavtMllTCA,3.250000,1.441725,36,390.194444,0.138507,0.222461,2,Harsh Critic,service_quality
1,-M7fUg7FrdGctKr5f_eMUQ,4.090909,1.341963,22,358.727273,0.215294,0.162739,3,Emotional Storyteller,ambience
2,-WM58wLjtlHlR91xVfM1FQ,4.041667,1.197068,24,632.666667,0.298114,0.206382,3,Emotional Storyteller,ambience
3,-qTtg1D3RidRa4cTB-ftwg,4.733333,0.703732,15,195.666667,0.425713,0.245910,0,Warm Optimist,NaN
4,02H49g16MdRoZKoX6IEoFA,4.272727,1.202451,22,406.545455,0.255776,0.355440,1,Reactive Reviewer,NaN
5,0650daOKAuufqymyOBe3cA,4.937500,0.250000,16,255.937500,0.478739,0.196268,0,Warm Optimist,NaN
6,06Yz-YYYa1U9PN37b6UniA,4.062500,1.123610,16,777.625000,0.316035,0.162744,3,Emotional Storyteller,ambience
7,0Tsu6-uhw_w9Z3W0Xlnazg,1.687500,1.138347,16,411.125000,0.093389,0.225517,2,Harsh Critic,service_quality
8,0xJwTzZuWOac7ufeTioeig,3.882353,1.363926,17,556.705882,0.234285,0.198699,3,Emotional Storyteller,ambience
9,175DuOm7IPiEy5f1KG9esA,3.470588,1.461326,34,646.705882,0.156587,0.192224,2,Harsh Critic,service_quality
10,1Dgjx4glo2Xex9hVwL_DTA,3.804348,1.275749,46,815.282609,0.219439,0.164072,3,Emotional Storyteller,ambience
11,1EiBjAbU_MlwMcEGsMO5Tw,4.344828,1.009804,29,632.000000,0.240194,0.121104,3,Emotional Storyteller,ambience

In [23]:
persona = persona_df.sample(
    4,
    random_state=42
).iloc[0]

persona

user_id               hGd6g2nZVraL17H4DnY1Dw
avg_rating                               4.0
rating_variance                     1.135924
review_count                              32
avg_review_length                  838.71875
avg_sentiment                       0.264413
sentiment_variance                  0.140242
cluster                                    3
archetype              Emotional Storyteller
dominant_value                      ambience
Name: 203, dtype: object

In [24]:
from src.recommender.behavioral_retrieval import (
    retrieve_behavioral_matches
)

results = retrieve_behavioral_matches(

    persona_row=persona,

    unified_behavior_df=unified_behavior_df,

    top_k=50
)

results[
    [
        "domain",
        "rating",
        "review_text"
    ]
].head(30)

,domain,rating,review_text
14210,goodreads,4.0,"Boy in a Band is a poignant, emotional and ver..."
14421,goodreads,5.0,Can you ever recapture the thrill of your firs...
17224,goodreads,5.0,Metamorphosis by Jennifer Carole Lewis is the ...
13900,goodreads,4.0,4.5 'Just Jump' Stars! \n Enter the giveaway f...
17245,goodreads,5.0,Note: I received an advanced reader's copy (AR...
13896,goodreads,5.0,"5 fighting stars!! \n ""I'll fight for us, but ..."
13924,goodreads,4.0,"Poignant story, beautifully written!! \n As pa..."
17271,goodreads,4.0,"Mapping Me: A Landscape of Women's Stories, ed..."
13913,goodreads,4.0,"Had the pleasure to read an early copy, and it..."
17302,goodreads,5.0,Simply breathtaking! A MUST READ! \n Life Unde...
13938,goodreads,5.0,"""Some seek the limelight and some hold the lig..."
13929,goodreads,5.0,"""For good or bad, all roads led back to him. P..."
13950,goodreads,4.0,"4.5 STARS!! \n ""Love is friendship set on fire..."
13942,goodreads,5.0,Fantastic friends-to-enemies story!! My heart ...
13962,goodreads,4.0,4.5 Stars \n Jane Harvey-Berrick delivers anot...
13976,goodreads,5.0,4.5 - 5 Heart-Stopping Stars \n This book is w...
13997,goodreads,5.0,"""We didn't always want what was right. We want..."
13994,goodreads,4.0,"4 - 4.5 Enchanting Stars!! \n Well, I certainl..."
14017,goodreads,5.0,"""You're only alive if you bruise."" \n WOW. I f..."
14031,goodreads,5.0,"""Together we flew and together we drifted down..."
14051,goodreads,5.0,"4.5 Emotionally Stunning Stars!! \n ""He was my..."
14050,goodreads,5.0,"""I kept my eyes closed. I couldn't bear for hi..."
5588,lagos_restaurants,5.0,Breeze is a very exclusive and remarkable beac...
10480,lagos_restaurants,3.5,Rhapsody Blues.\n\nTook the Mrs out for dinner...
14060,goodreads,5.0,4.5 sexy-Alpha stars!! \n Harper Sloan keeps g...
14080,goodreads,5.0,How can that rare beautiful be rendered irrele...
14112,goodreads,4.0,"Having read and loved Incandescent, I couldn't..."
24801,amazon_home,4.0,Obviously not one of Slim's crowning achieveme...
14130,goodreads,4.0,"4.5 stars!! Sexy, emotional, warm and very sat..."
14123,goodreads,4.0,4 sweetly emotional stars! \n Under the Orange...

Build:

Conversational recommendation generation
Context-aware recommendation orchestration
Multi-turn recommendation memory
Cross-domain taste transfer
Cold-start reasoning
Recommendation explanation engine

In [25]:
from src.recommender.recommendation_generation import *

In [26]:
# generate recommendations based on retrieved matches

from src.recommender.recommendation_generation import (
    generate_conversational_recommendations
)

recommendations = (
    generate_conversational_recommendations(

        persona_row=persona,

        retrieval_results=results,

        top_k=5
    )
)

recommendations

[{'domain': 'goodreads',
  'rating': 4.0,
  'recommendation_preview': 'Boy in a Band is a poignant, emotional and very sexy story of Morgan and Matthew, who meet as 12 year olds and in the Seventies. This is an extremely nostalgic coming of age story ',
  'explanation': 'Your interaction style resembles users who positively engage with these books and reading experiences.'},
 {'domain': 'goodreads',
  'rating': 5.0,
  'recommendation_preview': 'Can you ever recapture the thrill of your first love? T. Torrest has gifted us readers with a nostalgic, sweet, sexy and emotional story about two high schoolers trying to navigate',
  'explanation': 'As a Emotional Storyteller, you may appreciate these books and reading experiences because they align with your behavioral preferences and emotional tendencies.'},
 {'domain': 'goodreads',
  'rating': 5.0,
  'recommendation_preview': "Metamorphosis by Jennifer Carole Lewis is the second instalment in the Lalassu series. While the beginning doesn't seem to start where the other left off, it is a fair continuation",
  'explanation': 'This recommendation reflects your inferred emotional and behavioral preferences across domains.'},
 {'domain': 'goodreads',
  'rating': 4.0,
  'recommendation_preview': "4.5 'Just Jump' Stars! \n Enter the giveaway for a SIGNED paperback HERE \n K. Bromberg continues to surprise with this strikingly mature and deeply-felt romance! Although Zander is ",
  'explanation': 'This recommendation reflects your inferred emotional and behavioral preferences across domains.'},
 {'domain': 'goodreads',
  'rating': 5.0,
  'recommendation_preview': "Note: I received an advanced reader's copy (ARC) of Bound by Spells in exchange for an honest review. \n What a blast! \n Bound by Spells, the second instalment in the Bound series b",
  'explanation': 'As a Emotional Storyteller, you may appreciate these books and reading experiences because they align with your behavioral preferences and emotional tendencies.'}]

This is explainable agentic recommendation and begins to satisfy TASK B REQUIREMENTS on
- Personalized recommendations,	
- Contextual retrieval,
- Conversational recommendations,	
- Cross-domain reasoning,	
- Cold-start support,	
- Agentic reasoning.

UPGRADE MULTI-TURN RECOMMENDATION MEMORY

Because Task B explicitly wants multiturn scenarios, We now make recommendations evolve, adapt, and remember prior interactions.

In [27]:
# TEST MEMORY
# This section tests the recommendation memory module by simulating user interactions with the generated recommendations. 
# It stores these interactions and retrieves the recommendation history to build a multi-turn context for future recommendations.

from src.recommender.recommendation_memory import (

    store_recommendation_interaction,

    retrieve_recommendation_history,

    build_multiturn_context
)

In [28]:
# STORE INTERACTIONS
# Simulate user interactions with the generated recommendations

for recommendation in recommendations:

    store_recommendation_interaction(

        user_id="user_001",

        recommendation=recommendation
    )

In [29]:
# RETRIEVE HISTORY
# This retrieves the recommendation history for the user, which can be used to build a multi-turn context for future recommendations.

history = retrieve_recommendation_history(
    "user_001"
)

history

[{'domain': 'goodreads',
  'rating': 4.0,
  'recommendation_preview': 'Boy in a Band is a poignant, emotional and very sexy story of Morgan and Matthew, who meet as 12 year olds and in the Seventies. This is an extremely nostalgic coming of age story ',
  'explanation': 'Your interaction style resembles users who positively engage with these books and reading experiences.'},
 {'domain': 'goodreads',
  'rating': 5.0,
  'recommendation_preview': 'Can you ever recapture the thrill of your first love? T. Torrest has gifted us readers with a nostalgic, sweet, sexy and emotional story about two high schoolers trying to navigate',
  'explanation': 'As a Emotional Storyteller, you may appreciate these books and reading experiences because they align with your behavioral preferences and emotional tendencies.'},
 {'domain': 'goodreads',
  'rating': 5.0,
  'recommendation_preview': "Metamorphosis by Jennifer Carole Lewis is the second instalment in the Lalassu series. While the beginning doesn't seem to start where the other left off, it is a fair continuation",
  'explanation': 'This recommendation reflects your inferred emotional and behavioral preferences across domains.'},
 {'domain': 'goodreads',
  'rating': 4.0,
  'recommendation_preview': "4.5 'Just Jump' Stars! \n Enter the giveaway for a SIGNED paperback HERE \n K. Bromberg continues to surprise with this strikingly mature and deeply-felt romance! Although Zander is ",
  'explanation': 'This recommendation reflects your inferred emotional and behavioral preferences across domains.'},
 {'domain': 'goodreads',
  'rating': 5.0,
  'recommendation_preview': "Note: I received an advanced reader's copy (ARC) of Bound by Spells in exchange for an honest review. \n What a blast! \n Bound by Spells, the second instalment in the Bound series b",
  'explanation': 'As a Emotional Storyteller, you may appreciate these books and reading experiences because they align with your behavioral preferences and emotional tendencies.'}]

In [30]:
# BUILD MULTI-TURN CONTEXT
# This builds a multi-turn context for the user based on their interaction history, 
# which can be used to generate more personalized and context-aware recommendations in future interactions.

context = build_multiturn_context(
    "user_001"
)

print(context)

    User previously interacted with:
    ['goodreads', 'goodreads', 'goodreads', 'goodreads', 'goodreads']

UPGRADE: CONTEXT-AWARE RECOMMENDATION ORCHESTRATION

Build:

- mood-aware recommendations
- celebration-aware recommendations
- comfort-food reasoning
- Nigerian contextual adaptation

In [31]:
unified_behavior_df.to_csv(

    "../outputs/unified_behavior_dataset.csv",

    index=False
)

print("saved")

saved

In [32]:
import pandas as pd
import numpy as np
from textblob import TextBlob  # install if missing: pip install textblob

# Load unified data
unified_df = pd.read_csv("../outputs/unified_behavior_dataset.csv")

# Compute sentiment for each review (simple)
def get_sentiment(text):
    try:
        return TextBlob(str(text)).sentiment.polarity
    except:
        return 0.0

unified_df['sentiment'] = unified_df['review_text'].apply(get_sentiment)

# Group by user_id
persona_features = unified_df.groupby('user_id').agg({
    'rating': ['mean', 'std', 'count'],
    'review_text': lambda x: x.astype(str).str.len().mean(),
    'sentiment': ['mean', 'std']
}).reset_index()

# Flatten column names
persona_features.columns = [
    'user_id', 'avg_rating', 'rating_variance', 'review_count',
    'avg_review_length', 'avg_sentiment', 'sentiment_variance'
]

# Fill NaN variance (for users with 1 review)
persona_features['rating_variance'] = persona_features['rating_variance'].fillna(0)
persona_features['sentiment_variance'] = persona_features['sentiment_variance'].fillna(0)

print(f"Persona features shape: {persona_features.shape}")
print(persona_features.head())

Persona features shape: (18773, 7)
                  user_id  avg_rating  rating_variance  review_count  \
0  --4AjktZiHowEIBCMd4CZA         4.0              0.0             1
1  --vCeHrklS1DIep0QhorrA         4.0              0.0             1
2  -0KrCHEsOcjJ6N4k_k1A9A         4.0              0.0             1
3  -2MXx9Fk3IiCg2y559iI8Q         4.0              0.0             1
4  -4Pvmnz9Mej98xiz1w-FRQ         2.0              0.0             1

   avg_review_length  avg_sentiment  sentiment_variance
0              351.0       0.383333                 0.0
1              121.0       0.290741                 0.0
2              335.0       0.229167                 0.0
3              269.0       0.206250                 0.0
4              341.0       0.153906                 0.0

In [33]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

# Use persona_features from previous step
# Filter users with at least 5 reviews for meaningful clustering
min_reviews = 5
filtered = persona_features[persona_features['review_count'] >= min_reviews].copy()
print(f"Users with >= {min_reviews} reviews: {len(filtered)}")

# Select features for clustering
features = ['avg_rating', 'rating_variance', 'avg_review_length', 'avg_sentiment', 'sentiment_variance']
X = filtered[features].fillna(0)

# Scale
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# KMeans (use same n_clusters as before, e.g., 5)
n_clusters = 5
kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)
filtered['cluster'] = kmeans.fit_predict(X_scaled)

# Analyze clusters to assign archetype names
cluster_means = filtered.groupby('cluster')[features].mean()
print("\nCluster means:")
print(cluster_means)

# Assign archetype names based on interpretation
# You can adjust these labels based on the cluster_means output
def assign_archetype(cluster):
    mapping = {
        0: "Harsh Critic",      # low avg_rating, high variance
        1: "Emotional Storyteller",  # high sentiment, long reviews
        2: "Warm Optimist",      # social sensitivity
        3: "Deep Experience Analyst",  # moderate ratings, high review count
        4: "Reactive Reviewer"  # high avg_rating, low variance
    }
    return mapping.get(cluster, "Balanced Reviewer")

filtered['archetype'] = filtered['cluster'].apply(assign_archetype)

# Also add dominant_value based on archetype (same mapping as before)
archetype_to_dominant = {
    "Harsh Critic": "service_quality",
    "Emotional Storyteller": "ambience",
    "Warm Optimist": "social_proof",
    "Deep Experience Analyst": "food_quality",
    "Reactive Reviewer": "time_efficiency"
}
filtered['dominant_value'] = filtered['archetype'].map(archetype_to_dominant)

# Save new persona dataset
filtered.to_csv("../outputs/persona_dataset_v2.csv", index=False)
print("Saved persona_dataset_v2.csv with shape:", filtered.shape)

# Show sample
print(filtered[['user_id', 'archetype', 'dominant_value', 'review_count', 'avg_rating']].head())

Users with >= 5 reviews: 389

Cluster means:
         avg_rating  rating_variance  avg_review_length  avg_sentiment  \
cluster
0          4.072769         0.299247         214.450873       0.405064
1          3.433578         1.388215         482.816528       0.168415
2          4.064857         0.358228         300.313527       0.238541
3          4.021098         0.781140        3141.065928       0.178025
4          4.000022         0.361662         221.807770       0.263795

         sentiment_variance
cluster
0                  0.199262
1                  0.230463
2                  0.166472
3                  0.107600
4                  0.303596
Saved persona_dataset_v2.csv with shape: (389, 10)
                             user_id              archetype dominant_value  \
77  012515e5802b2e0f42915118c90fa04b          Warm Optimist   social_proof
78  012aa353140af13109d00ca36cdc0637  Emotional Storyteller       ambience
81  01ec1a320ffded6b2dd47833f2c8e4fb          Warm Optimist   social_proof
90  06bd41ab4c378a8c5a9d45c6b4779650  Emotional Storyteller       ambience
93  08920c9c72f03d03df72908ce393f7e7          Warm Optimist   social_proof

    review_count  avg_rating
77            44    4.204545
78            40    3.575000
81           998    4.334669
90            15    3.866667
93            39    4.307692

In [35]:
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

# Select features for clustering
cluster_features = ['avg_rating', 'rating_variance', 'review_count', 
                    'avg_review_length', 'avg_sentiment', 'sentiment_variance']

X = persona_features[cluster_features].fillna(0)

# Scale
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# KMeans (adjust n_clusters as needed; 5 is a good start)
kmeans = KMeans(n_clusters=5, random_state=42, n_init=10)
persona_features['cluster'] = kmeans.fit_predict(X_scaled)

# Select features for clustering
features_for_clustering = ['avg_rating', 'rating_variance', 'avg_review_length', 'avg_sentiment', 'sentiment_variance']
X = persona_features[features_for_clustering].fillna(0)

# Map cluster to archetype based on cluster centers (you can later rename)
# For now, assign generic names
# Group by cluster and compute mean feature values
cluster_profiles = persona_features.groupby('cluster')[features_for_clustering].mean()

print("Cluster profiles:")
print(cluster_profiles)

# Based on the profiles, manually assign archetype names
# Example logic – adjust thresholds based on your actual cluster_profiles output
archetype_map = {}

for i in range(5):  # 5 clusters
    row = cluster_profiles.loc[i]
    avg_r = row['avg_rating']
    var_r = row['rating_variance']
    sent = row['avg_sentiment']
    rev_len = row['avg_review_length']
    
    # Heuristic rules on cluster averages (not per-user)
    if avg_r < 2.5:
        archetype_map[i] = "Harsh Critic"
    elif avg_r > 4.2 and sent > 0.3:
        archetype_map[i] = "Emotional Storyteller"
    elif avg_r > 4.0 and rev_len > 200:
        archetype_map[i] = "Deep Experience Analyst"
    elif var_r > 1.5:
        archetype_map[i] = "Reactive Reviewer"   # high variance = inconsistent ratings
    elif avg_r > 4.0 and sent < 0.2:
        archetype_map[i] = "Warm Optimist"
    else:
        archetype_map[i] = "Balanced Reviewer"

# Apply to persona_features
persona_features['archetype'] = persona_features['cluster'].map(archetype_map)

# Map archetype to dominant_value (using your exact archetypes)
archetype_to_dominant = {
    "Harsh Critic": "service_quality",
    "Emotional Storyteller": "ambience",
    "Deep Experience Analyst": "food_quality",
    "Warm Optimist": "social_proof",
    "Reactive Reviewer": "time_efficiency",
    "Balanced Reviewer": "neutral"
}

persona_features['dominant_value'] = persona_features['archetype'].map(archetype_to_dominant)

# Check mapping
print(persona_features[['cluster', 'archetype', 'dominant_value']].drop_duplicates().sort_values('cluster'))

# Save updated persona file (now with all 18,773 users)
persona_features.to_csv("../outputs/persona_dataset_full.csv", index=False)
print("Saved persona_dataset_full.csv with", len(persona_features), "users")

Cluster profiles:
         avg_rating  rating_variance  avg_review_length  avg_sentiment  \
cluster
0          4.628308         0.002429         232.198343       0.376197
1          4.001629         0.443826         276.312314       0.301073
2          3.920625         0.005764        1746.792917       0.172668
3          3.667447         0.860816         824.678128       0.163780
4          2.023910         0.000300         336.427545      -0.023793

         sentiment_variance
cluster
0                  0.002422
1                  0.232131
2                  0.001376
3                  0.147677
4                  0.000462
    cluster                archetype   dominant_value
0         0    Emotional Storyteller         ambience
16        1  Deep Experience Analyst     food_quality
34        2        Balanced Reviewer          neutral
81        3        Balanced Reviewer          neutral
4         4             Harsh Critic  service_quality
Saved persona_dataset_full.csv with 18773 users

In [36]:
import pandas as pd

# Load unified dataset (original, without archetype)
unified_df = pd.read_csv("../outputs/unified_behavior_dataset.csv")

# Load newly created persona dataset with archetypes
persona_full = pd.read_csv("../outputs/persona_dataset_full.csv")

# Merge on user_id (left join keeps all reviews, adds archetype/dominant_value)
unified_with_archetype = unified_df.merge(
    persona_full[['user_id', 'archetype', 'dominant_value']],
    on='user_id',
    how='left'
)

# Check for any null archetype (users not in persona_full? Should be none now)
print("Null archetype count:", unified_with_archetype['archetype'].isnull().sum())

# Save
unified_with_archetype.to_csv("../outputs/unified_behavior_with_archetype.csv", index=False)
print("Saved unified_behavior_with_archetype.csv, shape:", unified_with_archetype.shape)

Null archetype count: 0
Saved unified_behavior_with_archetype.csv, shape: (28294, 8)